package resolver_user

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	graph_model "git.ctisoftware.vn/back-end/base/src/graph/generated/model"
	generated_user "git.ctisoftware.vn/back-end/base/src/graph/generated/user"
)

// AccountUpdate is the resolver for the accountUpdate field.
func (r *mutationResolver) AccountUpdate(ctx context.Context, data graph_model.AccountUpdate) (*graph_model.Account, error) {
	panic(fmt.Errorf("not implemented: AccountUpdate - accountUpdate"))
}

// AccountMe is the resolver for the accountMe field.
func (r *queryResolver) AccountMe(ctx context.Context) (*graph_model.Account, error) {
	panic(fmt.Errorf("not implemented: AccountMe - accountMe"))
}

// Mutation returns generated_user.MutationResolver implementation.
func (r *Resolver) Mutation() generated_user.MutationResolver { return &mutationResolver{r} }

// Query returns generated_user.QueryResolver implementation.
func (r *Resolver) Query() generated_user.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
